site_name: Database Helper
site_url: https://abhishekghoshh.github.io/database-helper

nav:
  - Home: index.md
  - Database Technologies: 
    - Database: database/introduction.md
    - Choosing the right database: database/choosing-the-right-database.md
    - Primary Key: database/primary-key.md
    - Database Index: database/indexing.md
    - B-Tree and B+ Tree: database/b-tree-and-b-plus-tree.md
    - LSM Tree: database/lsm-tree.md
    - Bloom Filters: database/bloom-filters.md
    - Sharding and Partition: database/sharding-and-partition.md
    - Scaling and Replication: database/scaling-and-replication.md
    - Denormalization: database/denormalization.md
    - Database Migration: database/migration.md
    - NoSQL: database/nosql.md
    - ORM: database/orm.md
    - Graph Database: database/graph-database.md
    - Vector Database: database/vector-database.md
    - Message Queues: database/message-queues.md
    - Build your own database: database/build-your-own-database.md
  - postgres:
    - Introduction: postgres/introduction.md  
    - Links: postgres/links.md
  - sql:
    - Introduction: sql/introduction.md
    - Leetcode: sql/leetcode.md
    - Links: sql/links.md 
  - redis:
    - Introduction: redis/001-introduction.md 
    - Links: redis/links.md
  - mongodb:
    - Introduction: mongodb/introduction.md
    - CRUD: mongodb/crud.md
    - Data Types: mongodb/data-types.md
    - Create: mongodb/create.md
    - Operators: mongodb/operators.md
    - Read: mongodb/read.md
    - Update: mongodb/update.md
    - Delete: mongodb/delete.md
    - Index: mongodb/index.md
    - Geospatial Data: mongodb/geospatial-data.md
    - Aggregation Framework: mongodb/aggregation-framework.md
    - Advance Commands: mongodb/advance-commands.md
    - Links: mongodb/links.md
  - kafka:
    - Introduction: kafka/introduction.md
    - Confluent vs Apache Kafka: kafka/kafka.md
    - Deploy on Docker: kafka/deploy-on-docker.md
    - Kafka Deploy on Docker (KRaft): kafka/kafka-deploy-on-docker.md
    - Kafbat UI: kafka/kafbat-ui.md
    - Links: kafka/links.md
  - neo4j:
    - Introduction: database/neo4j.md
  - sqlite:
    - Introduction: database/sqlite.md
  - elasticsearch:
    - Introduction: database/elastic-search.md
  - cassandra:
    - Introduction: database/cassandra.md
  - surrealDB:
    - Introduction: database/SurrealDB.md
  - rabbitMQ:
    - Introduction: database/rabbitMQ.md





theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search
  - mkdocs-pdf

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abhishekghoshh
    - icon: fontawesome/brands/twitter
      link: https://x.com/abhishek_ghoshh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhishek-ghosh-220679132/

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: |
  &copy; 2025 <a href="https://github.com/abhishekghoshh"  target="_blank" rel="noopener">Abhishek Ghosh</a>
